--Ufs 
INSERT INTO TUFS (NOME,SIGLA) 
select 'Acre' AS "NOME", 'AC' as "SIGLA"  FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Alagoas' AS "NOME", 'AL' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Amapá' AS "NOME", 'AP' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Amazonas' AS "NOME", 'AM' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Bahia' AS "NOME",'BA' FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Ceará' AS "NOME",'CE' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Distrito Federal' AS "NOME",'DF' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Espírito Santo' AS "NOME",'ES' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Goiás' AS "NOME",'GO' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Maranhão' AS "NOME",'MA' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Mato Grosso' AS "NOME",'MT' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Mato Grosso do Sul' AS "NOME",'MS' as "SIGLA"  FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Minas Gerais' AS "NOME",'MG' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Pará' AS "NOME",'PA' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Paraíba' AS "NOME",'PB' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Paraná' AS "NOME",'PR' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Pernambuco' AS "NOME",'PE' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Piauí' AS "NOME",'PI' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Rio de Janeiro' AS "NOME",'RJ' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Rio Grande do Norte' AS "NOME",'RN' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Rio Grande do Sul' AS "NOME",'RS' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Rondônia' AS "NOME",'RO' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Roraima' as "NOME",'RR' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Santa Catarina' AS "NOME",'SC' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'São Paulo' AS "NOME",'SP' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Sergipe' AS "NOME",'SE' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre')
union all 
select 'Tocantins' AS "NOME",'TO' as "SIGLA" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TUFS WHERE NOME='Acre');


--Cria a View do Gráfico
--CREATE or REPLACE VIEW VFINANCEIROANOMES ( ID, ANOREF, MESREF, RECEITA, VALOR) AS
--SELECT
--MAX(f.id) AS ID,
--extract(ISOYEAR FROM f.DTMOVIMENTO)  AS ANOREF,
--extract(MONTH FROM f.DTMOVIMENTO)  AS MESREF,
--f.receita as RECEITA,
--SUM(f.VLRFINANCEIRO) as VALOR
--FROM TFINANCEIROS f
--GROUP BY  
--extract(ISOYEAR FROM f.DTMOVIMENTO), 
--extract(MONTH FROM f.DTMOVIMENTO), 
--f.RECEITA;


--Cria as opções de ENUM
--INSERT INTO TPRODUTOSTIPO
--(ID, NOME)
--select 0 AS "ID", 'Todos' AS "NOME" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TPRODUTOSTIPO WHERE NOME='Todos')
--UNION ALL 
--select 1 AS "ID", 'Final' AS "NOME" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TPRODUTOSTIPO WHERE NOME='Final')
--UNION ALL 
--select 2 AS "ID", 'Base' AS "NOME" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TPRODUTOSTIPO WHERE NOME='Base')
--UNION ALL 
--select 3 AS "ID", 'Acabamento' AS "NOME" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TPRODUTOSTIPO WHERE NOME='Acabamento')
--UNION ALL 
--select 4 AS "ID", 'Acessório' AS "NOME" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TPRODUTOSTIPO WHERE NOME='Acessório')
--UNION ALL 
--select 5 AS "ID", 'Serviço' AS "NOME" FROM TDUAL WHERE NOT EXISTS (SELECT 1 FROM TPRODUTOSTIPO WHERE NOME='Serviço');
--
--
